### ISSUE TITLE
TASK - Limelight Library

### ISSUE THREAD

**Issue by sammcdo** [frc6995/NOMAD-Base-2020#13]
I'm thinking something similar to [4414s code here](https://github.com/Team4414/FRC-2019/blob/master/src/main/java/frc/util/Limelight.java) for the Limelight class and then a subsystem with methods to help with vision and auto vision.

**Comment by sammcdo** [comment]
---
 Name: Limelight Wrapper
 About: A convenience class for using a limelight.
 Issue: #13
---

#### **Description**
This class provides a handy tool for using a limelight on a robot.
It will provide options for both regular and 3d modes, getting common
network table values, setting the LED states, and setting the camera
mode and changing the pipeline.

### **Inputs**
Network tables
(Parameter: The name of each limelight's network table)
(Parameter: Whether the limelight is in 3d mode.)

### **Outputs**
Network Table values.

### **Constraints**
Get x, y, skew, pipeline, 3d position
Set LED mode, pipeline, camera mode
Make it sendable, so it is easily displayed on shuffleboard.

### **Design (Algorithm)**

#### Constructor:

- Parameters: Name of the network table to access, 3d mode on/off

#### Class Data:
- Horizontal FOV for convenience.
- Vertical FOV for convenience.
- Name of the network table to access.
- 3d mode enabled.
- Led States. (enum)
- Camera States. (enum)

#### Private Methods:

- get
	- Parameters: Name of network table entry to access.
	- Run a network table double request.
	- Return: The double value from Network Tables.
- getArray
	- Parameters: Name of network table entry to access.
	- Run a network table double array request.
	- Return: The double array from Network Tables.
- set
	- Parameters: Name of network table entry to access, the value to set.
	- Run a network table set double request.
- getTableName
	- Return: The name of the network table this limelight is using.

#### Public Methods:
- hasTarget
	- Check the network table entry for 'tv'.
	- Return the value of the entry as a boolean.
- getXOffset
	- Return: The value of network table 'tx'.
- getYOffset
	- Return: The value of network table 'ty'.
- getSkew
	- Return: The value of network table 'ts'.
- getPipeline
	- Return: The value of network table 'getpipe'.
- setPipeline
	- Parameter: The pipeline number to set.
	- Set the pipeline to the nuumber given using entry 'pipeline'.
- setLedMode
	- Parameter: The desired LED state.
	- Based on the given state, set the LED mode using entry 'ledMode'.
-  setCameraMode
	- Parameter: The desired camera mode.
	- Based on the given state set the camera mode using entry 'camMode'
- get3dPosition
	- If in 3d mode, return a Limelight3dPos containing the proper values from entry 'camtran'.
	- If not in 3d mode, return a Limelight3dPos containing all 0s.

#### Inner Classes:
- Limelight3dPos
	- Store the results of a limelight 3d position estimation.
	- x, y, z, pitch, yaw, and roll double variables.
	- Array containing all 6 values.

**Comment by sammcdo** [comment]
# LimelightS

## Dependencies

* WPILIB
* CTRE Phoenix API

## Description

* Subsystem for controlling the limelight and using it to control the robot.

## Inputs

* Network Tables

## Outputs

* Horizontal PID
* Vertical PID
* **Max**
  * Limelight Trajectory Following

## Actions

* PID Horizontal
* PID Vertical
* **Max**
  * Limelight Trajectory Following

## Constraints

* Outputs must be compatable with drivebase movement methods.
* **Max**
  * Trajectory following must be compatable with drivebase.

## Design

* Driver starts vision align
* PID outputs to drivebase.

### Variables

* The Limelight to control.
* A Moving Average for the horizontal input from the limelight.
  * Horizontal Moving Average max length
* A Moving Average for the vertical input from the limelight.
  * Vertical Moving Average max length
* A horizontal PID controller
* A vertical PID controller
* A variable to increment when checking if it is in range.

### Methods

* Get horizontal value
  * Add current reading from Limelight to Hor Moving Avg and return the averaged result.
* Get vertical value
  * Add current reading from Limelight to Vert Moving Avg and return the averaged result.
* Get horizontal PID output
* Get vertical PID output
* Check if at set point

**Comment by sammcdo** [comment]
This is what I did to drown my misery the first few weeks after quarantine. Check out branch sammcdo/limelightUpdate

**Comment by shueja** [comment]
Outdated.
