### ISSUE TITLE
COMMAND - Limelight Trajectory Align

### ISSUE THREAD

**Issue by sammcdo** [frc6995/NOMAD-Base-2020#15]
**Description**
Use trajectory following to align the robot in front of a target.

**Subsystem Requirements**
TBD

**Inputs**
Limelight Network Tables
TBD

**Outputs**
Sample and average the limelight's 3d position for accuracy (is this necessary?)
Generate a trajectory to place the robot in front of the target
Follow the trajectory to its completion and report final position

**Constraints**
TBD

**Design (Algorithm)**
TBD

**Comment by shueja** [comment]
We seem to have decided not to do this.
