### ISSUE TITLE
TASK - Trajectory Following

### ISSUE THREAD

**Issue by shueja-personal** [frc6995/NOMAD-Base-2020#7]
**Description**
Code the drivebase to be able to follow a trajectory.

**Requirements**
Follow tutorial at https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/trajectory-tutorial/trajectory-tutorial-overview.html

**Comment by sammcdo** [comment]
This needs updated with what we learned in season.

**Comment by shueja** [comment]
We ended up just reworking this completely. See demoDrivebase branch.
